"""Add Student_Profile table

Revision ID: 36845ff9cf33
Revises: 9b113ac033ca
Create Date: 2026-04-17 17:47:46.997884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36845ff9cf33'
down_revision = '9b113ac033ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student__profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student__profile')
    # ### end Alembic commands ###
