"""Add is_enrolled to course

Revision ID: b37f6191cc9d
Revises: 9e9bfbe85750
Create Date: 2026-04-27 15:04:06.184994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37f6191cc9d'
down_revision = '9e9bfbe85750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enrolled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('is_enrolled')

    # ### end Alembic commands ###
