"""Fix python naming convention createdAT

Revision ID: b51278bea477
Revises: e93536189548
Create Date: 2026-04-09 16:23:54.964735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b51278bea477'
down_revision = 'e93536189548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('createdAt')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('createdAt')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.drop_column('created_At')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.drop_column('created_At')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.drop_column('created_At')

    # ### end Alembic commands ###
